# Generated by Django 4.1.5 on 2023-01-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Workers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("surname", models.CharField(max_length=40)),
                ("patronymic", models.CharField(max_length=40)),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("OPER", "Operator"),
                            ("LEAD", "Leading Specialist"),
                            ("DIR_DEP", "Director of Department"),
                            ("HEAD_DEP", "Department head"),
                            ("CHIEF", "Chief Director"),
                        ],
                        default="OPER",
                        max_length=30,
                    ),
                ),
                ("employment_date", models.DateField()),
                ("salary", models.PositiveIntegerField()),
            ],
        ),
    ]
