# Generated by Django 4.1.1 on 2023-01-22 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hierarchy", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Workers",
            new_name="Worker",
        ),
    ]
