# Generated by Django 4.1.5 on 2023-01-23 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hierarchy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worker",
            name="boss",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="hierarchy.worker",
            ),
        ),
        migrations.AlterField(
            model_name="worker",
            name="position",
            field=models.CharField(
                choices=[
                    ("level_5", "5 level"),
                    ("level_4", "4 level"),
                    ("level_3", "3 level"),
                    ("level_2", "2 level"),
                    ("level_1", "1 level"),
                ],
                max_length=30,
            ),
        ),
    ]
