# Generated by Django 4.1.1 on 2023-01-22 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hierarchy", "0002_rename_workers_worker"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="boss",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="hierarchy.worker",
            ),
        ),
    ]
